name: "3D Print ERP"
description: "ERP systeem voor 3D print hobbyisten — jobs, klanten, kosten, offertes"
<<<<<<< HEAD
version: "2.0.169"
=======
version: "2.0.175"
>>>>>>> 9e74a472d816a0c57987634a6373dc9d737573ba
slug: "3d_print_erp"
init: false
arch:
  - amd64
homeassistant_api: true
hassio_api: true
ingress: true
ingress_port: 3000
panel_icon: mdi:printer-3d
panel_title: "3D Print ERP"
options:
  ha_token: ""
  smtp_user: "3dplezier@gmail.com"
  smtp_pass: ""
  smtp_from: "3dplezier@gmail.com"
schema:
  ha_token: str?
  smtp_user: str?
  smtp_pass: str?
  smtp_from: str?
map:
  - data
