name: "3D Print ERP"
description: "ERP systeem voor 3D print hobbyisten — jobs, klanten, kosten, offertes"
version: "2.0.162"
slug: "3d_print_erp"
init: false
arch:
  - amd64
homeassistant_api: true
hassio_api: true
ingress: true
ingress_port: 3000
panel_icon: mdi:printer-3d
panel_title: "3D Print ERP"
options:
  ha_token: ""
  smtp_user: "davidspiesschaert1@gmail.com"
  smtp_pass: "vnsh rdwi usve leei"
  smtp_from: "davidspiesschaert1@gmail.com"
schema:
  ha_token: str?
  smtp_user: str?
  smtp_pass: str?
  smtp_from: str?
map:
  - data
