name: "3D Print ERP"
description: "ERP systeem voor 3D print hobbyisten — jobs, klanten, kosten, offertes"
version: "1.0.14"
slug: "3d_print_erp"
init: false
arch:
  - amd64
homeassistant_api: true
hassio_api: true
ingress: true
ingress_port: 3000
panel_icon: mdi:printer-3d
panel_title: "3D Print ERP"
options:
  ha_token: ""
schema:
  ha_token: str?
map:
  - data
